version: '3.1'

services:
  db:
    image: task_10_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    build: .
