version: '3.1'

services:
  db:
    image: task_10_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8083:3306
    expose:
      - 8083
    build: .
